import {
  Activity, Airplay, AlertCircle, AlertTriangle, AlignCenter, AlignJustify, AlignLeft, AlignRight,
  Anchor, Aperture, Archive, ArrowDown, ArrowLeft, ArrowRight, ArrowUp, AtSign, Award,
  BarChart, Battery, Bell, BookOpen, Bookmark, Box, Briefcase, Brush, Bug,
  Calendar, Camera, Check, CheckCircle, ChevronDown, ChevronLeft, ChevronRight, ChevronUp,
  Circle, Clipboard, Clock, Cloud, Code, Code2, Coffee, Columns, Command, Compass,
  Copy, CreditCard, Crop,
  Database, Delete, DollarSign, Download, Droplet,
  Edit, Edit3, Eye, EyeOff,
  Facebook, FastForward, Feather, File, FilePlus, FileText, Film, Filter, Flag, Folder,
  FolderOpen, Frown,
  Gift, GitBranch, GitCommit, Github, Gitlab, Globe, Grid, Grid3X3,
  HardDrive, Hash, Headphones, Heart, HelpCircle, Home,
  Image, Inbox, Info, Instagram,
  Key,
  Layers, Layout, LayoutDashboard, LifeBuoy, Link, Linkedin, List, Loader, Lock, LogIn, LogOut,
  Mail, Map, MapPin, Maximize, Menu, MessageCircle, MessageSquare, Mic, Minimize, Minus,
  Monitor, Moon, MoreHorizontal, MoreVertical, MousePointer, Move, Music,
  Navigation, Newspaper,
  Package, Paperclip, Pause, Percent, Phone, PhoneCall, PieChart, Play, Plus, PlusCircle,
  Pocket, Power, Printer,
  Radio, RefreshCw, Repeat, Rocket, RotateCw, Rss,
  Save, Scissors, Search, Send, Server, Settings, Share, Share2, Shield, ShoppingBag,
  ShoppingCart, Shuffle, Sidebar, Slack, Slash, Sliders, Smartphone, Smile, SortAsc,
  SortDesc, Speaker, Star, StopCircle, Sun, Sunrise, Sunset,
  Tablet, Tag, Target, Terminal, Thermometer, ThumbsDown, ThumbsUp,   ToggleLeft, ToggleRight,
  Trash, Trash2, TrendingDown, TrendingUp, Truck, Tv, Twitch, Twitter, Type,
  Umbrella, Underline, Unlock, Upload, User, UserCheck, UserMinus, UserPlus, Users,
  Video, VideoOff, Volume, Volume1, Volume2, VolumeX,
  Watch, Wifi, Wind, Wrench,
  X, XCircle,
  Youtube,
  Zap, ZoomIn, ZoomOut,
} from 'lucide-react';

export const ICON_LIST = [
  { name: 'Activity', keywords: ['chart', 'pulse'], component: Activity },
  { name: 'Airplay', keywords: ['screen', 'mirror'], component: Airplay },
  { name: 'AlertCircle', keywords: ['warning', 'info'], component: AlertCircle },
  { name: 'AlertTriangle', keywords: ['warning', 'danger'], component: AlertTriangle },
  { name: 'AlignCenter', keywords: ['text', 'align'], component: AlignCenter },
  { name: 'AlignJustify', keywords: ['text', 'align'], component: AlignJustify },
  { name: 'AlignLeft', keywords: ['text', 'align'], component: AlignLeft },
  { name: 'AlignRight', keywords: ['text', 'align'], component: AlignRight },
  { name: 'Anchor', keywords: ['link', 'chain'], component: Anchor },
  { name: 'Aperture', keywords: ['camera', 'lens'], component: Aperture },
  { name: 'Archive', keywords: ['box', 'store'], component: Archive },
  { name: 'ArrowDown', keywords: ['direction'], component: ArrowDown },
  { name: 'ArrowLeft', keywords: ['direction'], component: ArrowLeft },
  { name: 'ArrowRight', keywords: ['direction'], component: ArrowRight },
  { name: 'ArrowUp', keywords: ['direction'], component: ArrowUp },
  { name: 'AtSign', keywords: ['email', 'address'], component: AtSign },
  { name: 'Award', keywords: ['prize', 'trophy'], component: Award },
  { name: 'BarChart', keywords: ['chart', 'stats'], component: BarChart },
  { name: 'Battery', keywords: ['power', 'energy'], component: Battery },
  { name: 'Bell', keywords: ['notification', 'alert'], component: Bell },
  { name: 'BookOpen', keywords: ['book', 'read'], component: BookOpen },
  { name: 'Bookmark', keywords: ['save', 'favorite'], component: Bookmark },
  { name: 'Box', keywords: ['package', 'cube'], component: Box },
  { name: 'Briefcase', keywords: ['work', 'job'], component: Briefcase },
  { name: 'Brush', keywords: ['paint', 'design'], component: Brush },
  { name: 'Bug', keywords: ['error', 'debug'], component: Bug },
  { name: 'Calendar', keywords: ['date', 'event'], component: Calendar },
  { name: 'Camera', keywords: ['photo', 'picture'], component: Camera },
  { name: 'Check', keywords: ['tick', 'done'], component: Check },
  { name: 'CheckCircle', keywords: ['success', 'done'], component: CheckCircle },
  { name: 'ChevronDown', keywords: ['arrow', 'expand'], component: ChevronDown },
  { name: 'ChevronLeft', keywords: ['arrow', 'back'], component: ChevronLeft },
  { name: 'ChevronRight', keywords: ['arrow', 'next'], component: ChevronRight },
  { name: 'ChevronUp', keywords: ['arrow', 'collapse'], component: ChevronUp },
  { name: 'Circle', keywords: ['shape'], component: Circle },
  { name: 'Clipboard', keywords: ['copy', 'paste'], component: Clipboard },
  { name: 'Clock', keywords: ['time', 'watch'], component: Clock },
  { name: 'Cloud', keywords: ['server', 'storage'], component: Cloud },
  { name: 'Code', keywords: ['programming', 'dev'], component: Code },
  { name: 'Code2', keywords: ['programming', 'dev'], component: Code2 },
  { name: 'Coffee', keywords: ['drink', 'break'], component: Coffee },
  { name: 'Columns', keywords: ['layout', 'grid'], component: Columns },
  { name: 'Command', keywords: ['terminal', 'keyboard'], component: Command },
  { name: 'Compass', keywords: ['direction', 'navigation'], component: Compass },
  { name: 'Copy', keywords: ['duplicate', 'clone'], component: Copy },
  { name: 'CreditCard', keywords: ['payment', 'money'], component: CreditCard },
  { name: 'Crop', keywords: ['image', 'cut'], component: Crop },
  { name: 'Database', keywords: ['storage', 'data'], component: Database },
  { name: 'Delete', keywords: ['remove', 'trash'], component: Delete },
  { name: 'DollarSign', keywords: ['money', 'price'], component: DollarSign },
  { name: 'Download', keywords: ['save', 'file'], component: Download },
  { name: 'Droplet', keywords: ['water', 'color'], component: Droplet },
  { name: 'Edit', keywords: ['write', 'pen'], component: Edit },
  { name: 'Edit3', keywords: ['write', 'pen'], component: Edit3 },
  { name: 'Eye', keywords: ['view', 'show'], component: Eye },
  { name: 'EyeOff', keywords: ['hide', 'hidden'], component: EyeOff },
  { name: 'Facebook', keywords: ['social', 'media'], component: Facebook },
  { name: 'FastForward', keywords: ['media', 'skip'], component: FastForward },
  { name: 'Feather', keywords: ['write', 'pen'], component: Feather },
  { name: 'File', keywords: ['document', 'page'], component: File },
  { name: 'FilePlus', keywords: ['add', 'new'], component: FilePlus },
  { name: 'FileText', keywords: ['document', 'article'], component: FileText },
  { name: 'Film', keywords: ['movie', 'video'], component: Film },
  { name: 'Filter', keywords: ['sort', 'search'], component: Filter },
  { name: 'Flag', keywords: ['report', 'mark'], component: Flag },
  { name: 'Folder', keywords: ['directory', 'file'], component: Folder },
  { name: 'FolderOpen', keywords: ['directory', 'file'], component: FolderOpen },
  { name: 'Frown', keywords: ['sad', 'emoji'], component: Frown },
  { name: 'Gift', keywords: ['present', 'reward'], component: Gift },
  { name: 'GitBranch', keywords: ['git', 'version'], component: GitBranch },
  { name: 'GitCommit', keywords: ['git', 'version'], component: GitCommit },
  { name: 'Github', keywords: ['social', 'code'], component: Github },
  { name: 'Gitlab', keywords: ['social', 'code'], component: Gitlab },
  { name: 'Globe', keywords: ['world', 'web'], component: Globe },
  { name: 'Grid', keywords: ['layout', 'table'], component: Grid },
  { name: 'Grid3X3', keywords: ['layout', 'table'], component: Grid3X3 },
  { name: 'HardDrive', keywords: ['disk', 'storage'], component: HardDrive },
  { name: 'Hash', keywords: ['number', 'tag'], component: Hash },
  { name: 'Headphones', keywords: ['music', 'audio'], component: Headphones },
  { name: 'Heart', keywords: ['like', 'love'], component: Heart },
  { name: 'HelpCircle', keywords: ['question', 'help'], component: HelpCircle },
  { name: 'Home', keywords: ['house', 'page'], component: Home },
  { name: 'Image', keywords: ['picture', 'photo'], component: Image },
  { name: 'Inbox', keywords: ['mail', 'email'], component: Inbox },
  { name: 'Info', keywords: ['information', 'about'], component: Info },
  { name: 'Instagram', keywords: ['social', 'media'], component: Instagram },
  { name: 'Key', keywords: ['password', 'security'], component: Key },
  { name: 'Layers', keywords: ['stack', 'depth'], component: Layers },
  { name: 'Layout', keywords: ['design', 'template'], component: Layout },
  { name: 'LayoutDashboard', keywords: ['dashboard', 'panel'], component: LayoutDashboard },
  { name: 'LifeBuoy', keywords: ['help', 'support'], component: LifeBuoy },
  { name: 'Link', keywords: ['url', 'chain'], component: Link },
  { name: 'Linkedin', keywords: ['social', 'media'], component: Linkedin },
  { name: 'List', keywords: ['menu', 'items'], component: List },
  { name: 'Loader', keywords: ['spinner', 'loading'], component: Loader },
  { name: 'Lock', keywords: ['security', 'protect'], component: Lock },
  { name: 'LogIn', keywords: ['enter', 'signin'], component: LogIn },
  { name: 'LogOut', keywords: ['exit', 'signout'], component: LogOut },
  { name: 'Mail', keywords: ['email', 'message'], component: Mail },
  { name: 'Map', keywords: ['location', 'place'], component: Map },
  { name: 'MapPin', keywords: ['location', 'marker'], component: MapPin },
  { name: 'Maximize', keywords: ['fullscreen', 'expand'], component: Maximize },
  { name: 'Menu', keywords: ['hamburger', 'nav'], component: Menu },
  { name: 'MessageCircle', keywords: ['chat', 'comment'], component: MessageCircle },
  { name: 'MessageSquare', keywords: ['chat', 'comment'], component: MessageSquare },
  { name: 'Mic', keywords: ['audio', 'record'], component: Mic },
  { name: 'Minimize', keywords: ['shrink', 'collapse'], component: Minimize },
  { name: 'Minus', keywords: ['remove', 'subtract'], component: Minus },
  { name: 'Monitor', keywords: ['screen', 'desktop'], component: Monitor },
  { name: 'Moon', keywords: ['dark', 'night'], component: Moon },
  { name: 'MoreHorizontal', keywords: ['menu', 'dots'], component: MoreHorizontal },
  { name: 'MoreVertical', keywords: ['menu', 'dots'], component: MoreVertical },
  { name: 'MousePointer', keywords: ['cursor', 'click'], component: MousePointer },
  { name: 'Move', keywords: ['drag', 'reorder'], component: Move },
  { name: 'Music', keywords: ['audio', 'song'], component: Music },
  { name: 'Navigation', keywords: ['direction', 'compass'], component: Navigation },
  { name: 'Newspaper', keywords: ['news', 'article'], component: Newspaper },
  { name: 'Package', keywords: ['box', 'delivery'], component: Package },
  { name: 'Paperclip', keywords: ['attach', 'file'], component: Paperclip },
  { name: 'Pause', keywords: ['media', 'stop'], component: Pause },
  { name: 'Percent', keywords: ['discount', 'rate'], component: Percent },
  { name: 'Phone', keywords: ['call', 'telephone'], component: Phone },
  { name: 'PhoneCall', keywords: ['call', 'dial'], component: PhoneCall },
  { name: 'PieChart', keywords: ['chart', 'stats'], component: PieChart },
  { name: 'Play', keywords: ['media', 'start'], component: Play },
  { name: 'Plus', keywords: ['add', 'new'], component: Plus },
  { name: 'PlusCircle', keywords: ['add', 'new'], component: PlusCircle },
  { name: 'Pocket', keywords: ['save', 'bookmark'], component: Pocket },
  { name: 'Power', keywords: ['off', 'shutdown'], component: Power },
  { name: 'Printer', keywords: ['print', 'paper'], component: Printer },
  { name: 'Radio', keywords: ['broadcast', 'audio'], component: Radio },
  { name: 'RefreshCw', keywords: ['reload', 'sync'], component: RefreshCw },
  { name: 'Repeat', keywords: ['loop', 'cycle'], component: Repeat },
  { name: 'Rocket', keywords: ['launch', 'start'], component: Rocket },
  { name: 'RotateCw', keywords: ['turn', 'spin'], component: RotateCw },
  { name: 'Rss', keywords: ['feed', 'news'], component: Rss },
  { name: 'Save', keywords: ['store', 'disk'], component: Save },
  { name: 'Scissors', keywords: ['cut', 'clip'], component: Scissors },
  { name: 'Search', keywords: ['find', 'magnify'], component: Search },
  { name: 'Send', keywords: ['submit', 'forward'], component: Send },
  { name: 'Server', keywords: ['host', 'computer'], component: Server },
  { name: 'Settings', keywords: ['config', 'gear'], component: Settings },
  { name: 'Share', keywords: ['social', 'send'], component: Share },
  { name: 'Share2', keywords: ['social', 'send'], component: Share2 },
  { name: 'Shield', keywords: ['security', 'protect'], component: Shield },
  { name: 'ShoppingBag', keywords: ['cart', 'buy'], component: ShoppingBag },
  { name: 'ShoppingCart', keywords: ['cart', 'buy'], component: ShoppingCart },
  { name: 'Shuffle', keywords: ['random', 'mix'], component: Shuffle },
  { name: 'Sidebar', keywords: ['panel', 'menu'], component: Sidebar },
  { name: 'Slack', keywords: ['social', 'chat'], component: Slack },
  { name: 'Slash', keywords: ['divide', 'separator'], component: Slash },
  { name: 'Sliders', keywords: ['adjust', 'settings'], component: Sliders },
  { name: 'Smartphone', keywords: ['mobile', 'phone'], component: Smartphone },
  { name: 'Smile', keywords: ['happy', 'emoji'], component: Smile },
  { name: 'SortAsc', keywords: ['order', 'sort'], component: SortAsc },
  { name: 'SortDesc', keywords: ['order', 'sort'], component: SortDesc },
  { name: 'Speaker', keywords: ['audio', 'sound'], component: Speaker },
  { name: 'Star', keywords: ['favorite', 'rating'], component: Star },
  { name: 'StopCircle', keywords: ['halt', 'end'], component: StopCircle },
  { name: 'Sun', keywords: ['light', 'day'], component: Sun },
  { name: 'Sunrise', keywords: ['morning', 'day'], component: Sunrise },
  { name: 'Sunset', keywords: ['evening', 'night'], component: Sunset },
  { name: 'Tablet', keywords: ['pad', 'mobile'], component: Tablet },
  { name: 'Tag', keywords: ['label', 'category'], component: Tag },
  { name: 'Target', keywords: ['aim', 'goal'], component: Target },
  { name: 'Terminal', keywords: ['console', 'command'], component: Terminal },
  { name: 'Thermometer', keywords: ['heat', 'temp'], component: Thermometer },
  { name: 'ThumbsDown', keywords: ['dislike', 'no'], component: ThumbsDown },
  { name: 'ThumbsUp', keywords: ['like', 'yes'], component: ThumbsUp },
  { name: 'ToggleLeft', keywords: ['switch', 'off'], component: ToggleLeft },
  { name: 'ToggleRight', keywords: ['switch', 'on'], component: ToggleRight },
  { name: 'Trash', keywords: ['delete', 'remove'], component: Trash },
  { name: 'Trash2', keywords: ['delete', 'remove'], component: Trash2 },
  { name: 'TrendingDown', keywords: ['chart', 'decline'], component: TrendingDown },
  { name: 'TrendingUp', keywords: ['chart', 'growth'], component: TrendingUp },
  { name: 'Truck', keywords: ['delivery', 'shipping'], component: Truck },
  { name: 'Tv', keywords: ['screen', 'display'], component: Tv },
  { name: 'Twitch', keywords: ['social', 'stream'], component: Twitch },
  { name: 'Twitter', keywords: ['social', 'media'], component: Twitter },
  { name: 'Type', keywords: ['text', 'font'], component: Type },
  { name: 'Umbrella', keywords: ['rain', 'weather'], component: Umbrella },
  { name: 'Underline', keywords: ['text', 'format'], component: Underline },
  { name: 'Unlock', keywords: ['security', 'open'], component: Unlock },
  { name: 'Upload', keywords: ['file', 'send'], component: Upload },
  { name: 'User', keywords: ['person', 'profile'], component: User },
  { name: 'UserCheck', keywords: ['person', 'verify'], component: UserCheck },
  { name: 'UserMinus', keywords: ['person', 'remove'], component: UserMinus },
  { name: 'UserPlus', keywords: ['person', 'add'], component: UserPlus },
  { name: 'Users', keywords: ['people', 'group'], component: Users },
  { name: 'Video', keywords: ['movie', 'film'], component: Video },
  { name: 'VideoOff', keywords: ['movie', 'off'], component: VideoOff },
  { name: 'Volume', keywords: ['audio', 'sound'], component: Volume },
  { name: 'Volume1', keywords: ['audio', 'sound'], component: Volume1 },
  { name: 'Volume2', keywords: ['audio', 'sound'], component: Volume2 },
  { name: 'VolumeX', keywords: ['audio', 'mute'], component: VolumeX },
  { name: 'Watch', keywords: ['time', 'clock'], component: Watch },
  { name: 'Wifi', keywords: ['network', 'signal'], component: Wifi },
  { name: 'Wind', keywords: ['weather', 'air'], component: Wind },
  { name: 'Wrench', keywords: ['tool', 'settings'], component: Wrench },
  { name: 'X', keywords: ['close', 'delete'], component: X },
  { name: 'XCircle', keywords: ['close', 'error'], component: XCircle },
  { name: 'Youtube', keywords: ['social', 'video'], component: Youtube },
  { name: 'Zap', keywords: ['lightning', 'fast'], component: Zap },
  { name: 'ZoomIn', keywords: ['search', 'magnify'], component: ZoomIn },
  { name: 'ZoomOut', keywords: ['search', 'shrink'], component: ZoomOut },
];

export function getIconComponent(name: string) {
  const item = ICON_LIST.find((i) => i.name === name);
  return item?.component || null;
}

